// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrrHuFMtnJhPFv7aK1mw3LKJJuyBSYaXI',
    appId: '1:375356092519:web:2c0d1867b3682bcc9364c2',
    messagingSenderId: '375356092519',
    projectId: 'university17-28d51',
    authDomain: 'university17-28d51.firebaseapp.com',
    storageBucket: 'university17-28d51.firebasestorage.app',
    measurementId: 'G-G6Z1XKTG29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHi2E9O90wL0DX18dyuMKrIPhuJ8n16uM',
    appId: '1:375356092519:android:af38e2b81b8d5a259364c2',
    messagingSenderId: '375356092519',
    projectId: 'university17-28d51',
    storageBucket: 'university17-28d51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACM97tBco8UeoFDrWDorwjAiiLt43-8VM',
    appId: '1:375356092519:ios:747ca330aca8358b9364c2',
    messagingSenderId: '375356092519',
    projectId: 'university17-28d51',
    storageBucket: 'university17-28d51.firebasestorage.app',
    androidClientId:
        '375356092519-3i3uab06oefsm6ufl7a7j9h7jbpr4bhr.apps.googleusercontent.com',
    iosClientId:
        '375356092519-vfbvdotod517pjclouvako341hau9ibf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrrHuFMtnJhPFv7aK1mw3LKJJuyBSYaXI',
    appId: '1:375356092519:web:505f6c650ad1b1bc9364c2',
    messagingSenderId: '375356092519',
    projectId: 'university17-28d51',
    authDomain: 'university17-28d51.firebaseapp.com',
    storageBucket: 'university17-28d51.firebasestorage.app',
    measurementId: 'G-GQ41BD5RYM',
  );
}
